image: golang:1.6

test:
    script:
        - go vet
        - mkdir -p "$GOPATH/src/gitlab.cern.ch/flutter"
        - ln -sfv "$(pwd -P)" "$GOPATH/src/gitlab.cern.ch/flutter"
        - cd "$GOPATH/src/gitlab.cern.ch/flutter/echelon"
        - go get -t
        - go test -v -cover -race

